### ISSUE TITLE
Return policy cannot be added

### ISSUE THREAD

**Issue by Michelvst** [202ecommerce/ebay2#20]
I have installed version 2.2.5 of the module and when selecting the returnpolicy in the listing setting, the dropdown menu 
for Returns within* and Who pays both don't show any options to select so I cannot configure the rest.

**Comment by Michelvst** [comment]
I unistalled the module, emptied all database tables related to the module and reinstalled.  Now it works fine.

**Comment by clotairer** [comment]
Thank you for your feedback !
