### ISSUE TITLE
Ebay synch error Shipping Profile

### ISSUE THREAD

**Issue by SarahRx** [202ecommerce/ebay2#22]
Hello, 
I can no longer synchronize my products on ebay. Each time, I get an error message: "37: The data entered for the tag is missing or invalid. Please consult your API documentation.(Item.SellerProfiles.SellerShippingProfile.ShippingProfileID)"
I don't understand, yesterday it was working fine.
I updated to version 2.2.6 but it doesn't change anything.

With the log, I can see that the Seller Shipping Profile is empty:
10/02/2023 14:09:36

 HEADERS : 
Array
(
    [0] => X-EBAY-API-COMPATIBILITY-LEVEL: 1225
    [1] => X-EBAY-API-DEV-NAME: 1db92af1-2824-4c45-8343-dfe68faa0280
    [2] => X-EBAY-API-APP-NAME: Prestash-70a5-419b-ae96-f03295c4581d
    [3] => X-EBAY-API-CERT-NAME: 71d26dc9-b36b-4568-9bdb-7cb8af16ac9b
    [4] => X-EBAY-API-CALL-NAME: AddFixedPriceItem
    [5] => X-EBAY-API-SITEID: 71
)
10/02/2023 14:09:36

<?xml version="1.0" encoding="utf-8"?><AddFixedPriceItem xmlns="urn:ebay:apis:eBLBaseComponents">
	<ErrorLanguage>fr_FR</ErrorLanguage>
	<WarningLevel>High</WarningLevel>
	<Item>
					<BestOfferDetails>
				<BestOfferEnabled>false</BestOfferEnabled>
			</BestOfferDetails>
		
					<SKU>prestashop-3160</SKU>
							<AutoPay>1</AutoPay>
		        
		<Title><![CDATA[Lot de 3 Bistouris Electriques EMC Dolley Statome T100 Type 324850]]></Title>
					<PictureDetails>
				<GalleryType>Gallery</GalleryType>
									<PhotoDisplay>PicturePack</PhotoDisplay>
													<PictureURL>https://i.ebayimg.com/00/s/NjAxWDQ1Mg==/z/GmMAAOSwWldj5R2e/$_1.JPG?set_id=2</PictureURL>
									<PictureURL>https://i.ebayimg.com/00/s/NjAxWDQ1Mg==/z/vnkAAOSwNU5j5R2h/$_1.JPG?set_id=2</PictureURL>
									<PictureURL>https://i.ebayimg.com/00/s/NjAxWDQ1Mg==/z/FY0AAOSwBdtj5R2i/$_1.JPG?set_id=2</PictureURL>
									<PictureURL>https://i.ebayimg.com/00/s/NjAxWDQ1Mg==/z/DnAAAOSwjsVj5R2k/$_1.JPG?set_id=2</PictureURL>
									<PictureURL>https://i.ebayimg.com/00/s/NjAxWDQ1Mg==/z/y-oAAOSweyVj5R2m/$_1.JPG?set_id=2</PictureURL>
							</PictureDetails>
				<Description><![CDATA[<link rel="stylesheet" type="text/css" href="https://www.alternup-medical.com/modules/ebay/views/css/ebay.css" /><p><link href="https://www.alternup-medical.com/modules/ebay/views/css/ebay.css" rel="stylesheet" type="text/css" /></p>
<table border="0" cellspacing="0" cellpadding="0" align="center">
<tbody>
<tr>
<td style="text-align: center;"> </td>
</tr>
<tr>
<td style="text-align: center;">
<p><a href="https://www.alternup-medical.com/fr" target="_blank"><img class="arrondi" src="https://www.alternup-medical.com/modules/ebay/LD%20BANNER.png" alt="" /></a></p>
</td>
</tr>
<tr style="text-align: center;">
<td>
<h1 align="center"><span class="bodyNameProductPrestashop">Lot de 3 Bistouris Electriques EMC Dolley Statome T100 Type 324850</span></h1>
</td>
</tr>
<tr style="text-align: center;">
<td>
<p align="center"><img src="https://www.alternup-medical.com/15994-large_default/ebay.jpg" class="bodyMainImageProductPrestashop" /></p>
</td>
</tr>
<tr style="text-align: center;" align="center">
<td>
<p style="text-align: center;"><img src="https://www.alternup-medical.com/15993-small_default/ebay.jpg" class="bodyFirstMediumImageProductPrestashop" /><img src="https://www.alternup-medical.com/15990-small_default/ebay.jpg" class="bodyMediumImageProductPrestashop" /><img src="https://www.alternup-medical.com/15991-small_default/ebay.jpg" class="bodyMediumImageProductPrestashop" /></p>
</td>
</tr>
<tr style="text-align: center;">
<td class="bodyProductPrestashop" style="text-align: center;"><br />
<p><span class="bodyNameProductPrestashop"><p>Lot de 3 Bistouris Electriques EMC Dolley Statome T100 Type 324850</p>
<p>Fourni avec les pédales sans les pièces à main</p></span></p>
<h5><strong>La vente comprend uniquement ce qui se trouve sur les photos <span style="color: #d20a11;">- The sale only includes what is on the pictures</span></strong></h5>
<p> </p>
<h5><strong>Livraison à l'international possible sur demande<span style="color: #d20a11;"> - International delivery available on request</span></strong></h5>
<p> </p>
<h5>Nos ventes sont régies par nos <a href="https://www.alternup-medical.com/fr/content/3-conditions-generales-de-ventes" target="_blank">Conditions Générales de Vente</a></h5>
<h5>Our sales are subject to our <a href="https://www.alternup-medical.com/en/content/3-sales-terms-and-conditions" target="_blank">Terms & Sales Conditions</a></h5>
<h5><strong>N'hésitez pas à nous contacter pour plus d'information <span style="color: #d20a11;">- Feel free to contact us for mor information</span></strong></h5>
<p> </p>
<p><img src="https://www.alternup-medical.com/modules/ebay/delivery%20payment%20ebay.png" alt="" width="945" height="220" /></p>
<p>Alternup Medical SAS est une entreprise Française immatriculée au registre du commerce. N° Siret : 81260523600023</p>
</td>
</tr>
</tbody>
</table>]]></Description>
		<PrimaryCategory>
			<CategoryID>185192</CategoryID>
		</PrimaryCategory>

		<ConditionID>3000</ConditionID>
					<StartPrice>432</StartPrice>
				<CategoryMappingAllowed>true</CategoryMappingAllowed>
		<Country>FR</Country>
	
		<Location>FR</Location>
		
		<Currency>EUR</Currency>
		<DispatchTimeMax>2</DispatchTimeMax>
		<ListingDuration>GTC</ListingDuration>
		<ListingType>FixedPriceItem</ListingType>
						<PostalCode>69490</PostalCode>
					<Quantity>1</Quantity>
				<ItemSpecifics>
					</ItemSpecifics>

		
		    <SellerProfiles>
        <SellerPaymentProfile>
            <PaymentProfileID>210496486015</PaymentProfileID>
            <PaymentProfileName>eBay Managed Payments 1cb5b9917f4b000</PaymentProfileName>
        </SellerPaymentProfile>

        <SellerReturnProfile>
            <ReturnProfileID>243206695015</ReturnProfileID>
            <ReturnProfileName>14 days 451aa4869e9a000</ReturnProfileName>
        </SellerReturnProfile>
        <SellerShippingProfile>
            <ShippingProfileID></ShippingProfileID>
            <ShippingProfileName></ShippingProfileName>
        </SellerShippingProfile>

    </SellerProfiles>

Can you help me?

Thank  
Sarah

**Comment by fpanico82** [comment]
Hi,
To solve the problem, I suggest deleting the shipping policies in the 'ebay_business_policies' table.
You can delete the existing conditions, with the button provided for this case in the "Tools" section.
The module will recreate the rules when the products are synchronised.
Francesco
202 ecommerce
