### ISSUE TITLE
[Feature] Add the possibility to retrieve relay point deliveries.

### ISSUE THREAD

**Issue by LameuleFR** [202ecommerce/ebay2#24]
Hello,

I think it would be really beneficial to the module if u implement the compatibility with the relay deliveries.
It is very often the cheapest and most requested delivery option by customers

Regards,
Benjamin

**Comment by LameuleFR** [comment]
I tried to add a carrier named MondialRelay and link it within the module but the modules do not import command anymore after adding this.

Looking at the importOrders or validateOrder method there is no specific condition who prevent module from importing the order. I'm still investigating..

**Comment by clotairer** [comment]
Hi,
As explained by chat, we cannot develop adherence between other module like mondial relais, ...
You propose to try to do a PR on this feature. Thank you.
Keep in touch.
