### ISSUE TITLE
Ebay ask to add UPIN number

### ISSUE THREAD

**Issue by FredoAWT** [202ecommerce/ebay2#25]
Hi, 

Ebay ask to add for each product this number reference. 

Explaination heere

https://www.ebay.fr/help/selling/all-about-selling/selling-internationally/extended-producer-responsibility-for-business-sellers?id=5314

This informations are in the product page, here in the website (see screenshot).

![screenshot-www ebay fr-2023 03 02-10_26_13](https://user-images.githubusercontent.com/90643664/222388721-99751277-d745-4208-9f13-37d60c88e7b4.png)
![screenshot-www ebay fr-2023 03 02-10_25_54](https://user-images.githubusercontent.com/90643664/222388725-af7773a3-d3b3-43c8-bc73-a443e0679574.png)
![screenshot-www ebay fr-2023 03 02-10_25_43](https://user-images.githubusercontent.com/90643664/222388727-4960b1d7-147a-4d94-a8c5-4a0dc0bfc0c8.png)

Do you have any idea to add this feature and synchronize ? We have more than 10.000 products...

**Comment by clotairer** [comment]
1) We stop adding new functionality, so if someone needs a new particular functionality, he can create PR.
2) As far as I understand, the additional fields the client talk about are required not for all categories. I suppose the clients will have the possibility to configure these fields on 2nd step of category configuration.
