### ISSUE TITLE
Mapping Condition

### ISSUE THREAD

**Issue by MaskDD** [202ecommerce/ebay2#26]
Hello, 

I can't edit this: 

"Associate PrestaShop features with eBay features"

One of the categories only offers eBay choices, and doesn't allow me to put in a variable.

The ideal for me would have been to be able to add my own feature "Card state" (because in my category there are several aesthetic grades) 

![2023-03-24_02h14_20](https://user-images.githubusercontent.com/86791754/227400076-44e8d7d0-dffe-4515-bd91-13f1c10913a0.png)

Can I fix this somehow? 

Thanks in advance

**Comment by fpanico82** [comment]
Hi,
table 'ebay_category_specific' has a field 'selection_mode'. 
If this field is '0' for some category then the module shows only ebay's choices
