### ISSUE TITLE
Can't connect to ebay

### ISSUE THREAD

**Issue by VinsMach** [202ecommerce/ebay2#3]
I have Prestashop 1.6.1.24 version and 1 hour ago I installed the module downloading it from here.
Now I can't connect my ebay's account anymore, it gives me this error
> Error code: 20.1.3: 2022-07-09 08:07:16: signin.ebay.com

**Comment by clotairer** [comment]
Hello,

Please try to upgrade into 2.2.4 > https://github.com/202ecommerce/ebay2/releases/tag/2.2.4-rc1
This issue should be fixed.

**Comment by clotairer** [comment]
@tom-combet My team confirm the popin don't block the process of token generation. Just wait about 1min.

A fix will be probably added in 2.2.5.

**Comment by tjsop** [comment]
Hi there
I have the same problem but i cant install the last version, when i insall the new version the old one stays, do i need to uninstall the old version first ? Normally we dont have too, its not recommanded but maybe here yes, thank you for your help

**Comment by numayos** [comment]
Hi,

I'm on version 2.2.6 and I'm having a similar problem and I don't know how to fix it.
When I click on "Create OAuth Token" I am redirected to the Ebay login page. Once connected, nothing happens.
I reconnect to Prestashop and redo the same operation in a loop. No "User Authorization Token" is generated.
Can you help me ?

--- fr version ---

Bonjour,
Je suis en version 2.2.6 et je rencontre un problème similaire et je ne sais pas comment le résoudre.
Lorsque je clique sur "Créer le Token OAuth" je suis redirigé vers la page de connexion Ebay. Une fois connecté, il ne se passe rien.
Je me reconnecte à Prestashop et refait la même manipulation en boucle. Aucun "Token d'autorisation utilisateur" n'est généré. 
Pouvez-vous m'aider ?

**Comment by MartianX** [comment]
> Hi,
> 
> I'm on version 2.2.6 and I'm having a similar problem and I don't know how to fix it. When I click on "Create OAuth Token" I am redirected to the Ebay login page. Once connected, nothing happens. I reconnect to Prestashop and redo the same operation in a loop. No "User Authorization Token" is generated. Can you help me ?
> 
> --- fr version ---
> 
> Bonjour, Je suis en version 2.2.6 et je rencontre un problème similaire et je ne sais pas comment le résoudre. Lorsque je clique sur "Créer le Token OAuth" je suis redirigé vers la page de connexion Ebay. Une fois connecté, il ne se passe rien. Je me reconnecte à Prestashop et refait la même manipulation en boucle. Aucun "Token d'autorisation utilisateur" n'est généré. Pouvez-vous m'aider ?

hello,
i have same behavior but only few products get exported all the rest are rejected.
Did you find any solution ?

**Comment by Baloo13001** [comment]
Salut,

Je suis sur la version 2.2.6 et j'ai un problème similaire et je ne sais pas comment le résoudre. Lorsque je clique sur "Créer un jeton OAuth", je suis redirigé vers la page de connexion Ebay. Une fois connecté, rien ne se passe. Je me reconnecte à Prestashop et refais la même opération en boucle. Aucun "jeton d'autorisation utilisateur" n'est généré. Pouvez-vous m'aider ?

**Comment by Baloo13001** [comment]
Hi,

I'm on version 2.2.6 and I have a similar problem and I don't know how to fix it. When I click on "Create an OAuth token", I am redirected to the Ebay login page. Once connected, nothing happens. I reconnect to Prestashop and repeat the same operation in a loop. No "user authorization token" is generated. Can you help me ?

**Comment by fpanico82** [comment]
Hi,
If the token was not generated after the permission on the eBay page, I suppose there are two possible causes:

1) An error in the process of the token generation. In this case, you have to look for the additional info in PrestaShop logs (use '[ebay]' as search input)

![Selection_533](https://github.com/202ecommerce/ebay2/assets/64893195/80749850-ee1e-4cba-a227-bfc4e942452d)


2) Another possible cause is a wrong URL for parameter 'Your auth accepted URL' in the token configuration page

![Selection_534](https://github.com/202ecommerce/ebay2/assets/64893195/c0d0763f-94a1-4168-b0b9-b843f1cab602)

Please check these elements

**Comment by Baloo13001** [comment]
Good morning ,fpanico82
Thank you for your help, I managed to put the token my I encounter a problem and I can't find it the profile remains blocked on the remaining task I attach the capture to you.
I need your help thank you
Cordially
Thierry
![Capture d’écran 2023-07-19 010308 (1)](https://github.com/202ecommerce/ebay2/assets/136246541/1a0ae3d8-767e-4cf0-903f-e3b19928dc3b)
