### ISSUE TITLE
Updating old 202 official module to last Github version 

### ISSUE THREAD

**Issue by couillaler** [202ecommerce/ebay2#4]
Hi,
I'm using the 2.2.2 version (bought to 202ecommerce few years ago [no more active business care help]) on my PS 1.7.8.7. ***
How do can I update to this last 2.2.4 (github version) without to lose any existing configuration ? Is this possible ?
Thanks,
Antoine
*** : for information, as 2.2.2 was not working anymore with ebay since 2022 (it was one of the purpose of the last official update from 202ecommerce), and as it was too expensive for me, I have not bought it and had desactivated the 2.2.2 version on my PS shop. I would be glad to update and reactivate it with this 2.2.4 version without to lose my existing module configuration.

**Comment by tom-combet** [comment]
I guess you can just import the new version in your PrestaShop and the upgrade process will start.
That's what I did after doing backups of the website just in case.

**Comment by clotairer** [comment]
Information of @tom-combet are right.

Just install the lastest zip here https://github.com/202ecommerce/ebay2/releases
