### ISSUE TITLE
September 1st zip missing

### ISSUE THREAD

**Issue by tom-combet** [202ecommerce/ebay2#5]
> A zip containing corrections made by 202 ecommerce will be published by September 1st 2022 on GitHub

Where is this zip? I have some bugs with the last version, for example the search doesn't work anymore through tables like rejected products, logs and so on.

**Comment by clotairer** [comment]
Lastest zip are here 
https://github.com/202ecommerce/ebay2/releases

2.2.4 was in prerelease between july until august and published the 1st september. PrestaShop addons store was in 2.2.3 until the 1st september. So respects our engagement.

But as long as code exists, bugs also exists. We didn’t say all bugs will be fixed the first of september…

We will continue à little bit more than expected. We started compatibility tests with PrestaShop 8.0. That’s our priority and we Hope to submit fixes in nexts monthes.
We have a 2.2.5 opened too on our side with some new fixes and security improvements. We will continue to publish new minor release in next weeks and monthes. The rythm and millestone are in « best effort ».

Without external helps and revenue, we will not spend time on minor bugs… sorry for that.
If you have an issue you can post it here with all details to reproduce it. After that, if you want to do a Pull Request we will be happy to approve it. Some other developer or 202 could also publish a fix. It depend the gravity.

Thanks

**Comment by tom-combet** [comment]
Thanks for the detailed answer. If there are only minor bugs, I'll try to debug them and open PR.

It's very good to know that you still take care of the evolution of the module. Updates are really important for this kind of module (when related to third services) and I was hesitating to switch to FastBay one.

**Comment by clotairer** [comment]
We have one year to find an new model for this addons. We warranty for our current customer the support of the module.
For a new merchant that start with eBay, he can test the module (and eBay) for free. After that it normal to ask about the good module and finaly choose an other solution like Fastbay (with is initially a fork of this module).
