### ISSUE TITLE
"error 21919303: The Brand object feature is missing." While the brand is filled in

### ISSUE THREAD

**Issue by fanfan7110** [202ecommerce/ebay2#8]
I am on version 2.2.4 of the ebay module and version 1.7.8.7 of prestashop. The shop is in 5 languages (FR UK SP IT DE). The module is intended for ebay fr.
For information The line "brand" is well informed in each article on all the shop but the module does not allow ebay the acceptance of synchronization.

All of my items are being rejected with: "21919303: The Brand item attribute is missing. Add Brand to this listing, enter a valid value, and try again.(The Brand item attribute is missing.)"

What is false, the brand is well registered for each article.

I am attaching two images to this message:
rejected.png which shows the error messages (88 rejections for the 88 articles sent) and brand.png which shows that the brand is correctly inserted in the article file.

![rejected](https://user-images.githubusercontent.com/47280587/189954813-fd6b7c20-9cce-4fb4-bdaf-78b76dba9892.PNG)
![brand](https://user-images.githubusercontent.com/47280587/189954844-c3afa914-d6bb-4dfc-9e3c-7e1caaaa3ead.PNG)

Thank you

**Comment by Artem202** [comment]
Most often, this error is due to the absence of a required characteristic in the product record (e.g. "Brand") that was set in [step 2 of the category synchronisation process](https://desk.202-ecommerce.com/portal/en/kb/articles/product-associations-between-ebay-and-prestashop).

You need to check your configuration for a feature Brand in step 2. . At this step you indicate which field in prestashop corresponds to which characteristic on ebay.

thx

**Comment by fanfan7110** [comment]
Thank you but I just retested again and the module does not offer the linking of database fields as shown in step 2 of the user manual. The module is given the main category of products and the module lists the products directly without asking for more information.
Step 2 is not done.

**Comment by fanfan7110** [comment]
Here are the screenshots:
First when you add a category the only page that appears is the one
![ajout catégorie](https://user-images.githubusercontent.com/47280587/190614974-13b1a059-4cd4-40b4-9a4c-b18423455b0b.PNG)

Then once validated we return to the listing without it asking for anything more. So no request between database areas
![Capture](https://user-images.githubusercontent.com/47280587/190615148-9b156736-6c64-475d-a3ce-08395a09ec4a.PNG)

**Comment by ig96net** [comment]
Hi there,

I am also experiencing the same issue at the moment. I was wondering if this problem is still ongoing or if there is a solution available? Thank you.

**Comment by fpanico82** [comment]
Hi,
Probably the cause of the problem is the authentication token. It might not be valid. I invite you to regenerate it.
Please refer to the guides on the module: https://desk.202-ecommerce.com/portal/en/kb/addons-prestashop-help-center/ebay-2-official

Francesco,
202 ecommerce

**Comment by MartianX** [comment]
hello,

I'm experiencing the same issue, even after checking the Oauth Token valid state.
Does anyone found a solution? Thanks in advance
